/** @typedef {{ id: string, name: string, count: number, icon: string, accent: string, description: string }} CategoryDef */

/** @type {CategoryDef[]} */
module.exports = [
  {
    id: 'adventure-platform',
    name: 'Adventure & Platform Games',
    count: 20,
    icon: '🏔',
    accent: '#5eead4',
    description: 'Explore worlds, clear obstacles, and reach the finish.',
  },
  {
    id: 'arcade',
    name: 'Arcade Games',
    count: 20,
    icon: '👾',
    accent: '#c8f542',
    description: 'Quick-play classics built around scores and reflexes.',
  },
  {
    id: 'action-shooter',
    name: 'Action & Shooter Games',
    count: 15,
    icon: '🎯',
    accent: '#ff6b4a',
    description: 'Fast combat, sharp aim, and non-stop action.',
  },
  {
    id: 'racing',
    name: 'Racing Games',
    count: 10,
    icon: '🏁',
    accent: '#5b8cff',
    description: 'Race across tracks, roads, and futuristic circuits.',
  },
  {
    id: 'puzzle-logic',
    name: 'Puzzle & Logic Games',
    count: 20,
    icon: '🧩',
    accent: '#ff4d8d',
    description: 'Solve patterns, mazes, and brain-teasing challenges.',
  },
  {
    id: 'match-3-merge',
    name: 'Match-3 & Merge Games',
    count: 10,
    icon: '💎',
    accent: '#d77bff',
    description: 'Match colorful pieces and combine items to progress.',
  },
  {
    id: 'word',
    name: 'Word Games',
    count: 8,
    icon: '🔤',
    accent: '#2ec4b6',
    description: 'Type, spell, and test your vocabulary.',
  },
  {
    id: 'educational',
    name: 'Educational Games',
    count: 10,
    icon: '🎓',
    accent: '#ffd166',
    description: 'Learn new skills through interactive play.',
  },
  {
    id: 'memory',
    name: 'Memory Games',
    count: 6,
    icon: '🧠',
    accent: '#a78bfa',
    description: 'Train recall, concentration, and visual memory.',
  },
  {
    id: 'sports',
    name: 'Sports Games',
    count: 7,
    icon: '🏆',
    accent: '#34d399',
    description: 'Compete across fields, courts, and arenas.',
  },
  {
    id: 'board',
    name: 'Board Games',
    count: 8,
    icon: '♟',
    accent: '#f59e0b',
    description: 'Classic tabletop strategy for the browser.',
  },
  {
    id: 'snake',
    name: 'Snake Games',
    count: 3,
    icon: '🐍',
    accent: '#84cc16',
    description: 'Grow longer, move carefully, and chase high scores.',
  },
  {
    id: 'music',
    name: 'Music Games',
    count: 2,
    icon: '♫',
    accent: '#f472b6',
    description: 'Follow rhythms, notes, and musical challenges.',
  },
  {
    id: 'kids-coloring',
    name: 'Kids & Coloring Games',
    count: 4,
    icon: '🎨',
    accent: '#fb7185',
    description: 'Friendly creative games made for younger players.',
  },
  {
    id: 'find-difference',
    name: 'Find the Difference Games',
    count: 4,
    icon: '🔎',
    accent: '#38bdf8',
    description: 'Inspect two scenes and spot every hidden change.',
  },
  {
    id: 'endless-runner-flying',
    name: 'Endless Runner & Flying Games',
    count: 8,
    icon: '🚀',
    accent: '#60a5fa',
    description: 'Keep moving, dodge hazards, and survive the distance.',
  },
  {
    id: 'simulation-time',
    name: 'Simulation & Time Management Games',
    count: 6,
    icon: '⏱',
    accent: '#22d3ee',
    description: 'Manage systems, resources, businesses, and time.',
  },
  {
    id: 'casino-skill',
    name: 'Casino & Skill Games',
    count: 29,
    icon: '♦',
    accent: '#ef4444',
    description: 'Cards, tables, and skill-based challenges.',
  },
  {
    id: 'casual-skill',
    name: 'Casual & Skill Games',
    count: 10,
    icon: '⚡',
    accent: '#f97316',
    description: 'Easy to start, satisfying to master.',
  },
];
