/** @typedef {{ id: string, name: string, category: string, folder: string, entry: string, tagline: string, genre: string, controls: string, accent: string, image?: string, setup?: 'npm-build'|'vite-build'|'static', serveRoot?: string, packageDir?: string, playPath?: string, overrideEntry?: boolean }} GameDef */

/** @type {GameDef[]} */
module.exports = [
  {
    id: 'astray',
    name: 'Gravity Ball Escape',
    category: 'puzzle-logic',
    folder: 'Astray',
    entry: 'index.html',
    image: '/launcher/thumbs/astray.jpg',
    tagline: '3D maze. Find the exit before you lose your mind.',
    genre: 'Puzzle',
    controls: 'WASD / Arrows',
    accent: '#3dd6c3',
    setup: 'static',
  },
  {
    id: 'breaklock',
    name: 'BreakLock',
    category: 'puzzle-logic',
    folder: 'breaklock',
    serveRoot: 'breaklock/public',
    entry: 'index.html',
    image: '/launcher/thumbs/breaklock.jpg',
    playPath: '/breaklock/',
    tagline: 'Crack the pattern lock. Mastermind meets Android.',
    genre: 'Puzzle',
    controls: 'Touch / Mouse',
    accent: '#ff6b4a',
    setup: 'npm-build',
    packageDir: 'breaklock',
  },
  {
    id: 'hexgl',
    name: 'Hover Craft',
    category: 'racing',
    folder: 'HexGL',
    entry: 'index.html',
    image: '/launcher/thumbs/hexgl.jpg',
    tagline: 'Futuristic WebGL racing at full throttle.',
    genre: 'Racing',
    controls: 'Arrows / WASD',
    accent: '#5b8cff',
    setup: 'static',
  },
  {
    id: 'hextris',
    name: 'Hextris',
    category: 'arcade',
    folder: 'hextris',
    entry: 'index.html',
    image: '/launcher/thumbs/hextris.jpg',
    tagline: 'Rotate the hex. Stack colors. Chase a high score.',
    genre: 'Arcade',
    controls: 'Left / Right',
    accent: '#c4f542',
    setup: 'static',
  },
  {
    id: 'mimstris',
    name: 'Mimstris',
    category: 'puzzle-logic',
    folder: 'mimstris',
    serveRoot: 'mimstris/dist',
    entry: 'index.html',
    image: '/launcher/thumbs/mimstris.jpg',
    tagline: 'Tetris-inspired puzzle chaos built with React.',
    genre: 'Puzzle',
    controls: 'WASD / Arrows / Enter',
    accent: '#ff4d8d',
    setup: 'vite-build',
    packageDir: 'mimstris',
  },
  {
    id: 'mk-js',
    name: 'Mortal Combat',
    category: 'action-shooter',
    folder: 'mk.js',
    serveRoot: 'mk.js/game',
    entry: 'index.html',
    image: '/launcher/thumbs/mk-js.jpg',
    tagline: 'Canvas fighter — local 2-player brawler.',
    genre: 'Fighting',
    controls: 'Keyboard (P1 & P2)',
    accent: '#e85d04',
    setup: 'static',
    overrideEntry: true,
  },
  {
    id: 'pacman-canvas',
    name: 'Pacman',
    category: 'arcade',
    folder: 'pacman-canvas',
    entry: 'index.htm',
    image: '/launcher/thumbs/pacman-canvas.jpg',
    tagline: 'Classic pac-dot chasing on HTML5 canvas.',
    genre: 'Arcade',
    controls: 'Arrows',
    accent: '#ffe566',
    setup: 'static',
  },
  {
    id: 'radius-raid',
    name: 'Radius Raid',
    category: 'action-shooter',
    folder: 'radius-raid-js13k',
    entry: 'index.html',
    image: '/launcher/thumbs/radius-raid.jpg',
    tagline: 'Bullet-hell survival from a js13k entry.',
    genre: 'Shooter',
    controls: 'Mouse / WASD',
    accent: '#7cf5ff',
    setup: 'static',
  },
  {
    id: 'tower-game',
    name: 'Tower Game',
    category: 'casual-skill',
    folder: 'tower_game',
    entry: 'index.html',
    image: '/launcher/thumbs/tower-game.jpg',
    tagline: 'Swing blocks. Stack a skyscraper. Don’t drop.',
    genre: 'Arcade',
    controls: 'Tap / Click',
    accent: '#f95240',
    setup: 'npm-build',
    packageDir: 'tower_game',
  },
  {
    id: 'typer',
    name: 'Typer',
    category: 'word',
    folder: 'typer',
    entry: 'typer.html',
    image: '/launcher/thumbs/typer.jpg',
    tagline: 'Type to shoot. Tower-defense typing frenzy.',
    genre: 'Typing',
    controls: 'Keyboard',
    accent: '#2ec4b6',
    setup: 'static',
  },
  {
    id: 'dino-adventure',
    name: 'Dino Adventure',
    category: 'adventure-platform',
    folder: 'Dino Adventure',
    serveRoot:
      'Dino Adventure/previews.customer.envatousercontent.com/files/366391597',
    entry: 'index.html',
    image: '/launcher/thumbs/dino-adventure.jpg',
    tagline: 'Little Dino Adventure (Construct 3)',
    genre: 'Adventure',
    controls: 'Touch / Keyboard',
    accent: '#5eead4',
    setup: 'static',
  },
  {
    id: 'find-difference',
    name: 'Find Seven Differences',
    category: 'find-difference',
    folder: 'find_difference',
    serveRoot:
      'find_difference/previews.customer.envatousercontent.com/files/262105350',
    entry: 'index.html',
    image: '/launcher/thumbs/find-difference.jpg',
    tagline: 'Spot all seven differences between two scenes.',
    genre: 'Find the Difference',
    controls: 'Mouse / Touch',
    accent: '#38bdf8',
    setup: 'static',
  },
  {
    id: 'horik-viking',
    name: 'Horik Viking',
    category: 'adventure-platform',
    folder: 'Horik_Viking',
    serveRoot:
      'Horik_Viking/previews.customer.envatousercontent.com/files/256191350',
    entry: 'index.html',
    image: '/launcher/thumbs/horik-viking.jpg',
    tagline: 'Battle enemies and explore a Viking platform adventure.',
    genre: 'Adventure',
    controls: 'Keyboard / Touch',
    accent: '#f59e0b',
    setup: 'static',
  },
  {
    id: 'turtle-jump',
    name: 'Turtle Jump',
    category: 'casual-skill',
    folder: 'Turtle-Jump',
    serveRoot:
      'Turtle-Jump/previews.customer.envatousercontent.com/files/284738881',
    entry: 'index.html',
    image: '/launcher/thumbs/turtle-jump.jpg',
    tagline: 'Tap to jump. Dodge bombs and grab power-ups as a speedy turtle.',
    genre: 'Casual',
    controls: 'Tap / Click',
    accent: '#22c55e',
    setup: 'static',
  },
  {
    id: 'fruit-adventure',
    name: 'Fruit Adventure',
    category: 'adventure-platform',
    folder: 'Fruit-Adventure',
    entry: 'index.html',
    image: '/launcher/thumbs/fruit-adventure.jpg',
    tagline: 'Pixel-art platformer — collect fruit, dodge foes, clear the stage.',
    genre: 'Platformer',
    controls: 'Keyboard / Touch',
    accent: '#fb7185',
    setup: 'static',
  },
  {
    id: 'gunfighter',
    name: 'Gunfighter',
    category: 'action-shooter',
    folder: 'GunFighter',
    serveRoot: 'GunFighter/game',
    entry: 'index.html',
    image: '/launcher/thumbs/gunfighter.jpg',
    tagline: 'Western gun platformer — shoot, dodge, and clear every stage.',
    genre: 'Shooter',
    controls: 'Keyboard / Touch',
    accent: '#ef4444',
    setup: 'static',
  },
  {
    id: 'basketball',
    name: 'Basketball Challenge',
    category: 'sports',
    folder: 'Basketball',
    serveRoot: 'Basketball/game/files/434651259',
    entry: 'index.html',
    image: '/launcher/thumbs/basketball.jpg',
    tagline: 'Sink the shot — aim, arc, and rack up baskets.',
    genre: 'Sports',
    controls: 'Touch / Mouse',
    accent: '#f97316',
    setup: 'static',
  },
  {
    id: 'space-eaters',
    name: 'Space Eaters',
    category: 'arcade',
    folder: 'SpaceEaters',
    serveRoot:
      'SpaceEaters/previews.customer.envatousercontent.com/files/505625246',
    entry: 'index.html',
    image: '/launcher/thumbs/space-eaters.jpg',
    tagline: 'Casual space arcade — eat, dodge, and chase a high score.',
    genre: 'Arcade',
    controls: 'Touch / Keyboard',
    accent: '#a78bfa',
    setup: 'static',
  },
  {
    id: 'science-quiz',
    name: 'Science Quiz',
    category: 'educational',
    folder: 'science-quiz',
    serveRoot: 'science-quiz/game',
    entry: 'index.html',
    image: '/launcher/thumbs/science-quiz.jpg',
    tagline: 'Test your science knowledge — answer, learn, and beat your score.',
    genre: 'Quiz',
    controls: 'Touch / Mouse',
    accent: '#ffd166',
    setup: 'static',
  },
  {
    id: 'shadow-world-adventure',
    name: 'Shadoworld Adventure',
    category: 'adventure-platform',
    folder: 'shadow_world_adventure',
    serveRoot: 'shadow_world_adventure/game',
    entry: 'index.html',
    image: '/launcher/thumbs/shadow-world-adventure.jpg',
    tagline: 'Pixel-art platformer — explore the shadows and clear every stage.',
    genre: 'Platformer',
    controls: 'Keyboard / Touch',
    accent: '#818cf8',
    setup: 'static',
  },
  {
    id: 'running-pumpkin',
    name: 'Running Pumpkin',
    category: 'endless-runner-flying',
    folder: 'running-pmpkin',
    serveRoot: 'running-pmpkin/game',
    entry: 'index.html',
    image: '/launcher/thumbs/running-pumpkin.jpg',
    tagline: 'Dash, jump, and blast obstacles as a speedy pumpkin runner.',
    genre: 'Runner',
    controls: 'Keyboard / Touch',
    accent: '#fb923c',
    setup: 'static',
  },
];
