/** @typedef {{ id: string, name: string, category: string, folder: string, entry: string, tagline: string, genre: string, controls: string, accent: string, image?: string, setup?: 'npm-build'|'vite-build'|'static', serveRoot?: string, packageDir?: string, playPath?: string, overrideEntry?: boolean }} GameDef */

/** @type {GameDef[]} */
module.exports = [
  {
    id: 'astray',
    name: 'Gravity Ball Escape',
    category: 'puzzle-logic',
    folder: 'Astray',
    entry: 'index.html',
    image: '/launcher/thumbs/astray.jpg',
    tagline: '3D maze. Find the exit before you lose your mind.',
    genre: 'Puzzle',
    controls: 'WASD / Arrows',
    accent: '#3dd6c3',
    setup: 'static',
  },
  {
    id: 'breaklock',
    name: 'BreakLock',
    category: 'puzzle-logic',
    folder: 'breaklock',
    serveRoot: 'breaklock/public',
    entry: 'index.html',
    image: '/launcher/thumbs/breaklock.jpg',
    playPath: '/breaklock/',
    tagline: 'Crack the pattern lock. Mastermind meets Android.',
    genre: 'Puzzle',
    controls: 'Touch / Mouse',
    accent: '#ff6b4a',
    setup: 'npm-build',
    packageDir: 'breaklock',
  },
  {
    id: 'hexgl',
    name: 'Hover Craft',
    category: 'racing',
    folder: 'HexGL',
    entry: 'index.html',
    image: '/launcher/thumbs/hexgl.jpg',
    tagline: 'Futuristic WebGL racing at full throttle.',
    genre: 'Racing',
    controls: 'Arrows / WASD',
    accent: '#5b8cff',
    setup: 'static',
  },
  {
    id: 'hextris',
    name: 'Hextris',
    category: 'arcade',
    folder: 'hextris',
    entry: 'index.html',
    image: '/launcher/thumbs/hextris.jpg',
    tagline: 'Rotate the hex. Stack colors. Chase a high score.',
    genre: 'Arcade',
    controls: 'Left / Right',
    accent: '#c4f542',
    setup: 'static',
  },
  {
    id: 'mimstris',
    name: 'Mimstris',
    category: 'puzzle-logic',
    folder: 'mimstris',
    serveRoot: 'mimstris/dist',
    entry: 'index.html',
    image: '/launcher/thumbs/mimstris.jpg',
    tagline: 'Tetris-inspired puzzle chaos built with React.',
    genre: 'Puzzle',
    controls: 'WASD / Arrows / Enter',
    accent: '#ff4d8d',
    setup: 'vite-build',
    packageDir: 'mimstris',
  },
  {
    id: 'mk-js',
    name: 'Mortal Combat',
    category: 'action-shooter',
    folder: 'mk.js',
    serveRoot: 'mk.js/game',
    entry: 'index.html',
    image: '/launcher/thumbs/mk-js.jpg',
    tagline: 'Canvas fighter — local 2-player brawler.',
    genre: 'Fighting',
    controls: 'Keyboard (P1 & P2)',
    accent: '#e85d04',
    setup: 'static',
    overrideEntry: true,
  },
  {
    id: 'pacman-canvas',
    name: 'Pacman',
    category: 'arcade',
    folder: 'pacman-canvas',
    entry: 'index.htm',
    image: '/launcher/thumbs/pacman-canvas.jpg',
    tagline: 'Classic pac-dot chasing on HTML5 canvas.',
    genre: 'Arcade',
    controls: 'Arrows',
    accent: '#ffe566',
    setup: 'static',
  },
  {
    id: 'radius-raid',
    name: 'Radius Raid',
    category: 'action-shooter',
    folder: 'radius-raid-js13k',
    entry: 'index.html',
    image: '/launcher/thumbs/radius-raid.jpg',
    tagline: 'Bullet-hell survival from a js13k entry.',
    genre: 'Shooter',
    controls: 'Mouse / WASD',
    accent: '#7cf5ff',
    setup: 'static',
  },
  {
    id: 'tower-game',
    name: 'Tower Game',
    category: 'casual-skill',
    folder: 'tower_game',
    entry: 'index.html',
    image: '/launcher/thumbs/tower-game.jpg',
    tagline: 'Swing blocks. Stack a skyscraper. Don’t drop.',
    genre: 'Arcade',
    controls: 'Tap / Click',
    accent: '#f95240',
    setup: 'npm-build',
    packageDir: 'tower_game',
  },
  {
    id: 'typer',
    name: 'Typer',
    category: 'word',
    folder: 'typer',
    entry: 'typer.html',
    image: '/launcher/thumbs/typer.jpg',
    tagline: 'Type to shoot. Tower-defense typing frenzy.',
    genre: 'Typing',
    controls: 'Keyboard',
    accent: '#2ec4b6',
    setup: 'static',
  },
  {
    id: 'dino-adventure',
    name: 'Dino Adventure',
    category: 'adventure-platform',
    folder: 'Dino Adventure',
    serveRoot:
      'Dino Adventure/previews.customer.envatousercontent.com/files/366391597',
    entry: 'index.html',
    image: '/launcher/thumbs/dino-adventure.jpg',
    tagline: 'Little Dino Adventure (Construct 3)',
    genre: 'Adventure',
    controls: 'Touch / Keyboard',
    accent: '#5eead4',
    setup: 'static',
  },
  {
    id: 'find-difference',
    name: 'Find Seven Differences',
    category: 'find-difference',
    folder: 'find_difference',
    serveRoot:
      'find_difference/previews.customer.envatousercontent.com/files/262105350',
    entry: 'index.html',
    image: '/launcher/thumbs/find-difference.jpg',
    tagline: 'Spot all seven differences between two scenes.',
    genre: 'Find the Difference',
    controls: 'Mouse / Touch',
    accent: '#38bdf8',
    setup: 'static',
  },
  {
    id: 'horik-viking',
    name: 'Horik Viking',
    category: 'adventure-platform',
    folder: 'Horik_Viking',
    serveRoot:
      'Horik_Viking/previews.customer.envatousercontent.com/files/256191350',
    entry: 'index.html',
    image: '/launcher/thumbs/horik-viking.jpg',
    tagline: 'Battle enemies and explore a Viking platform adventure.',
    genre: 'Adventure',
    controls: 'Keyboard / Touch',
    accent: '#f59e0b',
    setup: 'static',
  },
  {
    id: 'turtle-jump',
    name: 'Turtle Jump',
    category: 'casual-skill',
    folder: 'Turtle-Jump',
    serveRoot:
      'Turtle-Jump/previews.customer.envatousercontent.com/files/284738881',
    entry: 'index.html',
    image: '/launcher/thumbs/turtle-jump.jpg',
    tagline: 'Tap to jump. Dodge bombs and grab power-ups as a speedy turtle.',
    genre: 'Casual',
    controls: 'Tap / Click',
    accent: '#22c55e',
    setup: 'static',
  },
  {
    id: 'fruit-adventure',
    name: 'Fruit Adventure',
    category: 'adventure-platform',
    folder: 'Fruit-Adventure',
    entry: 'index.html',
    image: '/launcher/thumbs/fruit-adventure.jpg',
    tagline: 'Pixel-art platformer — collect fruit, dodge foes, clear the stage.',
    genre: 'Platformer',
    controls: 'Keyboard / Touch',
    accent: '#fb7185',
    setup: 'static',
  },
  {
    id: 'gunfighter',
    name: 'Gunfighter',
    category: 'action-shooter',
    folder: 'GunFighter',
    serveRoot: 'GunFighter/game',
    entry: 'index.html',
    image: '/launcher/thumbs/gunfighter.jpg',
    tagline: 'Western gun platformer — shoot, dodge, and clear every stage.',
    genre: 'Shooter',
    controls: 'Keyboard / Touch',
    accent: '#ef4444',
    setup: 'static',
  },
  {
    id: 'basketball',
    name: 'Basketball Challenge',
    category: 'sports',
    folder: 'Basketball',
    serveRoot: 'Basketball/game/files/434651259',
    entry: 'index.html',
    image: '/launcher/thumbs/basketball.jpg',
    tagline: 'Sink the shot — aim, arc, and rack up baskets.',
    genre: 'Sports',
    controls: 'Touch / Mouse',
    accent: '#f97316',
    setup: 'static',
  },
  {
    id: 'space-eaters',
    name: 'Space Eaters',
    category: 'arcade',
    folder: 'SpaceEaters',
    serveRoot:
      'SpaceEaters/previews.customer.envatousercontent.com/files/505625246',
    entry: 'index.html',
    image: '/launcher/thumbs/space-eaters.jpg',
    tagline: 'Casual space arcade — eat, dodge, and chase a high score.',
    genre: 'Arcade',
    controls: 'Touch / Keyboard',
    accent: '#a78bfa',
    setup: 'static',
  },
  {
    id: 'science-quiz',
    name: 'Science Quiz',
    category: 'educational',
    folder: 'science-quiz',
    serveRoot: 'science-quiz/game',
    entry: 'index.html',
    image: '/launcher/thumbs/science-quiz.jpg',
    tagline: 'Test your science knowledge — answer, learn, and beat your score.',
    genre: 'Quiz',
    controls: 'Touch / Mouse',
    accent: '#ffd166',
    setup: 'static',
  },
  {
    id: 'shadow-world-adventure',
    name: 'Shadoworld Adventure',
    category: 'adventure-platform',
    folder: 'shadow_world_adventure',
    serveRoot: 'shadow_world_adventure/game',
    entry: 'index.html',
    image: '/launcher/thumbs/shadow-world-adventure.jpg',
    tagline: 'Pixel-art platformer — explore the shadows and clear every stage.',
    genre: 'Platformer',
    controls: 'Keyboard / Touch',
    accent: '#818cf8',
    setup: 'static',
  },
  {
    id: 'running-pumpkin',
    name: 'Running Pumpkin',
    category: 'endless-runner-flying',
    folder: 'running-pmpkin',
    serveRoot: 'running-pmpkin/game',
    entry: 'index.html',
    image: '/launcher/thumbs/running-pumpkin.jpg',
    tagline: 'Dash, jump, and blast obstacles as a speedy pumpkin runner.',
    genre: 'Runner',
    controls: 'Keyboard / Touch',
    accent: '#fb923c',
    setup: 'static',
  },
  {
    id: 'jojo-run',
    name: 'JoJo Run',
    category: 'endless-runner-flying',
    folder: 'jo jo run',
    serveRoot:
      'jo jo run/previews.customer.envatousercontent.com/files/293781175',
    entry: 'index.html',
    image: '/launcher/thumbs/jojo-run.jpg',
    tagline: 'Run, jump, and collect coins in a colorful endless chase.',
    genre: 'Runner',
    controls: 'Keyboard / Touch',
    accent: '#f472b6',
    setup: 'static',
  },
  {
    id: 'super-t-trix',
    name: 'Super T-Trix',
    category: 'puzzle-logic',
    folder: 'super-t-trix',
    entry: 'index.html',
    image: '/launcher/thumbs/super-t-trix.jpg',
    tagline: 'Stack blocks, clear rows, and chase a Tetris-style high score.',
    genre: 'Puzzle',
    controls: 'Touch / Keyboard',
    accent: '#22d3ee',
    setup: 'static',
  },
  {
    id: 'air-strike',
    name: 'Air Strike',
    category: 'action-shooter',
    folder: 'air-strike',
    serveRoot: 'air-strike/game',
    entry: 'index.html',
    image: '/launcher/thumbs/air-strike.jpg',
    tagline: 'Pilot a chopper, fire missiles, and complete every air mission.',
    genre: 'Shooter',
    controls: 'Keyboard / Touch',
    accent: '#38bdf8',
    setup: 'static',
  },
  {
    id: 'block-breaker',
    name: 'Block Breaker',
    category: 'arcade',
    folder: 'block-breaker',
    serveRoot: 'block-breaker/game',
    entry: 'index.html',
    image: '/launcher/thumbs/block-breaker.jpg',
    tagline: 'Bounce the ball, smash the blocks, and clear each level.',
    genre: 'Arcade',
    controls: 'Touch / Mouse',
    accent: '#facc15',
    setup: 'static',
  },
  {
    id: 'sweet-memory-game',
    name: 'Sweet Memory Game',
    category: 'memory',
    folder: 'sweet-memory-game',
    serveRoot: 'sweet-memory-game/game',
    entry: 'index.html',
    image: '/launcher/thumbs/sweet-memory-game.jpg',
    tagline: 'Flip the cards, match the pairs, and train your memory.',
    genre: 'Memory',
    controls: 'Touch / Mouse',
    accent: '#f9a8d4',
    setup: 'static',
  },
  {
    id: 'defence-battle',
    name: 'Defense Battle',
    category: 'action-shooter',
    folder: 'defence-battle',
    serveRoot: 'defence-battle/game',
    entry: 'index.html',
    image: '/launcher/thumbs/defence-battle.jpg',
    tagline: 'Defend your base — blast waves of enemies before they break through.',
    genre: 'Shooter',
    controls: 'Keyboard / Touch',
    accent: '#f87171',
    setup: 'static',
  },
  {
    id: 'skateboard',
    name: 'Skateboard Challenge',
    category: 'endless-runner-flying',
    folder: 'skateboard-challange',
    serveRoot:
      'skateboard-challange/previews.customer.envatousercontent.com/files/404157209',
    entry: 'index.html',
    image: '/launcher/thumbs/skateboard.jpg',
    tagline: 'Ollie, grind, and collect coins in an endless skate run.',
    genre: 'Runner',
    controls: 'Keyboard / Touch',
    accent: '#94a3b8',
    setup: 'static',
  },
  {
    id: 'rock-music',
    name: 'Rock Music Game',
    category: 'music',
    folder: 'rock-music',
    serveRoot:
      'rock-music/previews.customer.envatousercontent.com/files/366378565',
    entry: 'index.html',
    image: '/launcher/thumbs/rock-music.jpg',
    tagline: 'Hit the notes in time — a Guitar Hero–style rock rhythm challenge.',
    genre: 'Music',
    controls: 'Touch / Keyboard',
    accent: '#e879f9',
    setup: 'static',
  },
  {
    id: 'puzzle-game-boys',
    name: 'Puzzle Game Boys',
    category: 'puzzle-logic',
    folder: 'puzzle-game-boys',
    serveRoot: 'puzzle-game-boys/game',
    entry: 'index.html',
    image: '/launcher/thumbs/puzzle-game-boys.jpg',
    tagline: 'Slide, match, and solve — a classic puzzle challenge for kids.',
    genre: 'Puzzle',
    controls: 'Touch / Mouse',
    accent: '#60a5fa',
    setup: 'static',
  },
  {
    id: 'barbarian-vs-mummy',
    name: 'Barbarian VS Mummy',
    category: 'adventure-platform',
    folder: 'barbarian-vs-mummy',
    serveRoot: 'barbarian-vs-mummy/game',
    entry: 'index.html',
    image: '/launcher/thumbs/barbarian-vs-mummy.jpg',
    tagline: 'Slash through tombs and mummies in a pixel platform adventure.',
    genre: 'Platformer',
    controls: 'Keyboard / Touch',
    accent: '#d97706',
    setup: 'static',
  },
  {
    id: 'christmas-memory',
    name: 'Christmas Memory Game',
    category: 'memory',
    folder: 'christmas-memory',
    serveRoot: 'christmas-memory/game',
    entry: 'index.html',
    image: '/launcher/thumbs/christmas-memory.jpg',
    tagline: 'Match festive pairs and train your holiday memory skills.',
    genre: 'Memory',
    controls: 'Touch / Mouse',
    accent: '#ef4444',
    setup: 'static',
  },
  {
    id: 'country-hangman',
    name: 'Countries Hangman',
    category: 'word',
    folder: 'country-hangman',
    serveRoot: 'country-hangman/game',
    entry: 'index.html',
    image: '/launcher/thumbs/country-hangman.jpg',
    tagline: 'Guess the country letter by letter before the hangman wins.',
    genre: 'Word',
    controls: 'Touch / Mouse',
    accent: '#2ec4b6',
    setup: 'static',
  },
  {
    id: 'halloween-memory',
    name: 'Halloween Memory Game',
    category: 'memory',
    folder: 'halloween-memory',
    entry: 'index.html',
    image: '/launcher/thumbs/halloween-memory.jpg',
    tagline: 'Flip spooky cards and match every Halloween pair.',
    genre: 'Memory',
    controls: 'Touch / Mouse',
    accent: '#fb923c',
    setup: 'static',
  },
  {
    id: 'pop-it',
    name: 'Pop It Fidget',
    category: 'casual-skill',
    folder: 'pop-it',
    serveRoot:
      'pop-it/previews.customer.envatousercontent.com/files/349418796',
    entry: 'index.html',
    image: '/launcher/thumbs/pop-it.jpg',
    tagline: 'Relax and pop every bubble in this fidget toy challenge.',
    genre: 'Casual',
    controls: 'Touch / Mouse',
    accent: '#f472b6',
    setup: 'static',
  },
  {
    id: 'stone-smacker',
    name: 'Stone Smacker',
    category: 'puzzle-logic',
    folder: 'stone-smacker',
    serveRoot:
      'stone-smacker/previews.customer.envatousercontent.com/files/347597920',
    entry: 'index.html',
    image: '/launcher/thumbs/stone-smacker.jpg',
    tagline: 'Smash stones and clear the path in a pixel puzzle adventure.',
    genre: 'Puzzle',
    controls: 'Touch / Mouse',
    accent: '#a8a29e',
    setup: 'static',
  },
  {
    id: 'guitar',
    name: 'Neon Guitar',
    category: 'music',
    folder: 'guitar',
    serveRoot:
      'guitar/previews.customer.envatousercontent.com/files/343655291',
    entry: 'index.html',
    image: '/launcher/thumbs/guitar.jpg',
    tagline: 'Hit neon notes on beat in a Guitar Hero–style rhythm game.',
    genre: 'Music',
    controls: 'Keyboard / Touch',
    accent: '#c026d3',
    setup: 'static',
  },
  {
    id: 'redhead-knight',
    name: 'Redhead Knight',
    category: 'adventure-platform',
    folder: 'redhead-knight',
    serveRoot:
      'redhead-knight/previews.customer.envatousercontent.com/files/340017685',
    entry: 'index.html',
    image: '/launcher/thumbs/redhead-knight.jpg',
    tagline: 'Jump, slash, and adventure through a platformer knight quest.',
    genre: 'Platformer',
    controls: 'Keyboard / Touch',
    accent: '#dc2626',
    setup: 'static',
  },
  {
    id: 'neon-snake',
    name: 'Neon Snake',
    category: 'snake',
    folder: 'neon-snake',
    serveRoot:
      'neon-snake/previews.customer.envatousercontent.com/files/325645024',
    entry: 'index.html',
    image: '/launcher/thumbs/neon-snake.jpg',
    tagline: 'Glow, grow, and dodge walls in a neon snake classic.',
    genre: 'Snake',
    controls: 'Keyboard / Touch',
    accent: '#84cc16',
    setup: 'static',
  },
  {
    id: 'drift-king',
    name: 'Drift Challenge',
    category: 'racing',
    folder: 'drift-king',
    serveRoot:
      'drift-king/previews.customer.envatousercontent.com/files/390117056',
    entry: 'index.html',
    image: '/launcher/thumbs/drift-king.jpg',
    tagline: 'Slide into corners and master every drift challenge.',
    genre: 'Racing',
    controls: 'Keyboard / Touch',
    accent: '#5b8cff',
    setup: 'static',
  },
  {
    id: 'snake-ladder',
    name: 'Snake YO',
    category: 'snake',
    folder: 'snake-ladder',
    serveRoot:
      'snake-ladder/previews.customer.envatousercontent.com/files/388884462',
    entry: 'index.html',
    image: '/launcher/thumbs/snake-ladder.jpg',
    tagline: 'Eat, grow, and survive in a sleek snake challenge.',
    genre: 'Snake',
    controls: 'Keyboard / Touch',
    accent: '#a3e635',
    setup: 'static',
  },
  {
    id: 'scary-run',
    name: 'Scary Maze',
    category: 'casual-skill',
    folder: 'scary-run',
    serveRoot:
      'scary-run/previews.customer.envatousercontent.com/files/388183105',
    entry: 'index.html',
    image: '/launcher/thumbs/scary-run.jpg',
    tagline: 'Navigate a creepy first-person maze without losing your nerve.',
    genre: 'Maze',
    controls: 'Keyboard / Touch',
    accent: '#7f1d1d',
    setup: 'static',
  },
  {
    id: 'kill-zombies',
    name: 'Kill The Zombies',
    category: 'action-shooter',
    folder: 'kill-zombies',
    serveRoot:
      'kill-zombies/previews.customer.envatousercontent.com/files/386917321',
    entry: 'index.html',
    image: '/launcher/thumbs/kill-zombies.jpg',
    tagline: 'FPS mayhem — aim fast and clear the zombie horde.',
    genre: 'Shooter',
    controls: 'Mouse / Keyboard',
    accent: '#65a30d',
    setup: 'static',
  },
  {
    id: 'police-chase',
    name: 'Police Chase',
    category: 'action-shooter',
    folder: 'police-chase',
    serveRoot:
      'police-chase/previews.customer.envatousercontent.com/files/383431467',
    entry: 'index.html',
    image: '/launcher/thumbs/police-chase.jpg',
    tagline: 'Side-scrolling chase action — catch the target before they escape.',
    genre: 'Action',
    controls: 'Keyboard / Touch',
    accent: '#1d4ed8',
    setup: 'static',
  },
  {
    id: 'crypto-plicker',
    name: 'Crypto Plinko',
    category: 'casino-skill',
    folder: 'crypto-plicker',
    serveRoot:
      'crypto-plicker/previews.customer.envatousercontent.com/files/379913196',
    entry: 'index.html',
    image: '/launcher/thumbs/crypto-plicker.jpg',
    tagline: 'Drop the puck and chase big crypto-style Plinko payouts.',
    genre: 'Casino',
    controls: 'Touch / Mouse',
    accent: '#f59e0b',
    setup: 'static',
  },
  {
    id: 'sweet-crush',
    name: 'Sweet Crush',
    category: 'match-3-merge',
    folder: 'sweet-crush',
    serveRoot:
      'sweet-crush/previews.customer.envatousercontent.com/files/378998363',
    entry: 'index.html',
    image: '/launcher/thumbs/sweet-crush.jpg',
    tagline: 'Match sweets, clear the board, and crush every level.',
    genre: 'Match-3',
    controls: 'Touch / Mouse',
    accent: '#ec4899',
    setup: 'static',
  },
  {
    id: 'snowman-hunting',
    name: 'Beat The Snowmen',
    category: 'action-shooter',
    folder: 'snowman-hunting',
    serveRoot:
      'snowman-hunting/previews.customer.envatousercontent.com/files/401085762',
    entry: 'index.html',
    image: '/launcher/thumbs/snowman-hunting.jpg',
    tagline: 'Cartoon FPS — aim and blast every snowman in sight.',
    genre: 'Shooter',
    controls: 'Mouse / Keyboard',
    accent: '#38bdf8',
    setup: 'static',
  },
  {
    id: 'geography-quiz',
    name: 'Geography Quiz for Kids',
    category: 'educational',
    folder: 'geography-quiz',
    serveRoot:
      'geography-quiz/previews.customer.envatousercontent.com/files/399069742',
    entry: 'index.html',
    image: '/launcher/thumbs/geography-quiz.jpg',
    tagline: 'Learn the world — answer geography questions made for kids.',
    genre: 'Quiz',
    controls: 'Touch / Mouse',
    accent: '#ffd166',
    setup: 'static',
  },
  {
    id: 'unicorn-puzzle',
    name: 'Unicorn Puzzle',
    category: 'puzzle-logic',
    folder: 'unicorn-puzzle',
    serveRoot:
      'unicorn-puzzle/previews.customer.envatousercontent.com/files/397690219',
    entry: 'index.html',
    image: '/launcher/thumbs/unicorn-puzzle.jpg',
    tagline: 'Slide and solve magical unicorn puzzle pieces.',
    genre: 'Puzzle',
    controls: 'Touch / Mouse',
    accent: '#e879f9',
    setup: 'static',
  },
  {
    id: 'frog-cross',
    name: 'Frogie Cross The Road',
    category: 'arcade',
    folder: 'frog-cross',
    serveRoot:
      'frog-cross/previews.customer.envatousercontent.com/files/397329561',
    entry: 'index.html',
    image: '/launcher/thumbs/frog-cross.jpg',
    tagline: 'Help Frogie hop across traffic and reach the other side.',
    genre: 'Arcade',
    controls: 'Keyboard / Touch',
    accent: '#22c55e',
    setup: 'static',
  },
  {
    id: 'letter-memory',
    name: 'Letters Memory',
    category: 'memory',
    folder: 'letter-memory',
    serveRoot:
      'letter-memory/previews.customer.envatousercontent.com/files/396602133',
    entry: 'index.html',
    image: '/launcher/thumbs/letter-memory.jpg',
    tagline: 'Match letter pairs and sharpen your memory skills.',
    genre: 'Memory',
    controls: 'Touch / Mouse',
    accent: '#a78bfa',
    setup: 'static',
  },
  {
    id: 'space-war',
    name: 'Invaders War',
    category: 'arcade',
    folder: 'space-war',
    serveRoot:
      'space-war/previews.customer.envatousercontent.com/files/396438431',
    entry: 'index.html',
    image: '/launcher/thumbs/space-war.jpg',
    tagline: 'Classic space-invader arcade — blast waves of alien ships.',
    genre: 'Arcade',
    controls: 'Keyboard / Touch',
    accent: '#c8f542',
    setup: 'static',
  },
  {
    id: 'cute-cats',
    name: 'Cute Cats 2048',
    category: 'puzzle-logic',
    folder: 'cute-cats',
    serveRoot:
      'cute-cats/previews.customer.envatousercontent.com/files/392820986',
    entry: 'index.html',
    image: '/launcher/thumbs/cute-cats.jpg',
    tagline: 'Merge adorable cats in a cozy 2048-style puzzle.',
    genre: 'Puzzle',
    controls: 'Touch / Keyboard',
    accent: '#fb7185',
    setup: 'static',
  },
  {
    id: 'break-count',
    name: 'Break Count',
    category: 'puzzle-logic',
    folder: 'break-count',
    serveRoot:
      'break-count/previews.customer.envatousercontent.com/files/505379753',
    entry: 'index.html',
    image: '/launcher/thumbs/break-count.jpg',
    tagline: 'Break blocks and count your way to the next puzzle clear.',
    genre: 'Puzzle',
    controls: 'Touch / Mouse',
    accent: '#38bdf8',
    setup: 'static',
  },
  {
    id: 'rainbow-word-search',
    name: 'Rainbow Word Search',
    category: 'word',
    folder: 'rainbow-word-search',
    serveRoot:
      'rainbow-word-search/previews.customer.envatousercontent.com/files/450524206',
    entry: 'index.html',
    image: '/launcher/thumbs/rainbow-word-search.jpg',
    tagline: 'Find hidden words in a colorful rainbow word search.',
    genre: 'Word',
    controls: 'Touch / Mouse',
    accent: '#2ec4b6',
    setup: 'static',
  },
  {
    id: 'pinball-master',
    name: 'Pinball Master',
    category: 'arcade',
    folder: 'pinball-master',
    serveRoot:
      'pinball-master/previews.customer.envatousercontent.com/files/450201947',
    entry: 'index.html',
    image: '/launcher/thumbs/pinball-master.jpg',
    tagline: 'Flippers ready — rack up points in classic pinball arcade action.',
    genre: 'Arcade',
    controls: 'Keyboard / Touch',
    accent: '#f97316',
    setup: 'static',
  },
  {
    id: 'cute-animal-memories',
    name: 'Cute Animals Memory Challenge',
    category: 'memory',
    folder: 'cute-animal-memories',
    serveRoot:
      'cute-animal-memories/previews.customer.envatousercontent.com/files/448144275',
    entry: 'index.html',
    image: '/launcher/thumbs/cute-animal-memories.jpg',
    tagline: 'Match adorable animal pairs and train your memory.',
    genre: 'Memory',
    controls: 'Touch / Mouse',
    accent: '#f9a8d4',
    setup: 'static',
  },
  {
    id: 'ninja-plumber',
    name: 'Ninja Plumber',
    category: 'adventure-platform',
    folder: 'ninja-plumber',
    serveRoot:
      'ninja-plumber/previews.customer.envatousercontent.com/files/444204893',
    entry: 'index.html',
    image: '/launcher/thumbs/ninja-plumber.jpg',
    tagline: 'Side-scrolling ninja plumber adventure — jump, dash, and clear stages.',
    genre: 'Platformer',
    controls: 'Keyboard / Touch',
    accent: '#ef4444',
    setup: 'static',
  },
  {
    id: 'rocket-balance',
    name: 'Rocket Balance',
    category: 'casual-skill',
    folder: 'rocket-balance',
    serveRoot:
      'rocket-balance/previews.customer.envatousercontent.com/files/434014726',
    entry: 'index.html',
    image: '/launcher/thumbs/rocket-balance.jpg',
    tagline: 'Keep the rocket balanced and survive as long as you can.',
    genre: 'Casual',
    controls: 'Touch / Keyboard',
    accent: '#60a5fa',
    setup: 'static',
  },
  {
    id: 'neon-crush',
    name: 'Neon Crush',
    category: 'match-3-merge',
    folder: 'neon-crush',
    serveRoot:
      'neon-crush/previews.customer.envatousercontent.com/files/433998739',
    entry: 'index.html',
    image: '/launcher/thumbs/neon-crush.jpg',
    tagline: 'Match neon gems and crush every glowing puzzle level.',
    genre: 'Match-3',
    controls: 'Touch / Mouse',
    accent: '#d946ef',
    setup: 'static',
  },
  {
    id: 'burger-pixel',
    name: 'Ultra Pixel Burgeria',
    category: 'simulation-time',
    folder: 'burger-pixel',
    serveRoot:
      'burger-pixel/previews.customer.envatousercontent.com/files/434422424',
    entry: 'index.html',
    image: '/launcher/thumbs/burger-pixel.jpg',
    tagline: 'Run a pixel burger shop — cook, serve, and keep customers happy.',
    genre: 'Simulation',
    controls: 'Touch / Mouse',
    accent: '#f59e0b',
    setup: 'static',
  },
  {
    id: 'rocket-balance-even-odd',
    name: 'Rocket Balance Even Odd',
    category: 'educational',
    folder: 'rocket-balance-even-odd',
    serveRoot:
      'rocket-balance-even-odd/previews.customer.envatousercontent.com/files/429877854',
    entry: 'index.html',
    image: '/launcher/thumbs/rocket-balance-even-odd.jpg',
    tagline: 'Balance the rocket while learning even and odd numbers.',
    genre: 'Educational',
    controls: 'Touch / Keyboard',
    accent: '#ffd166',
    setup: 'static',
  },
  {
    id: 'history-quiz',
    name: 'History Quiz',
    category: 'educational',
    folder: 'history-quiz',
    serveRoot:
      'history-quiz/previews.customer.envatousercontent.com/files/423364718',
    entry: 'index.html',
    image: '/launcher/thumbs/history-quiz.jpg',
    tagline: 'Test your knowledge of history one question at a time.',
    genre: 'Quiz',
    controls: 'Touch / Mouse',
    accent: '#c4a574',
    setup: 'static',
  },
  {
    id: 'gluttonous-snake',
    name: 'Gluttonous Snake',
    category: 'snake',
    folder: 'gluttonous-snake',
    serveRoot:
      'gluttonous-snake/previews.customer.envatousercontent.com/files/409366169',
    entry: 'index.html',
    image: '/launcher/thumbs/gluttonous-snake.jpg',
    tagline: 'Eat, grow longer, and survive in a classic snake challenge.',
    genre: 'Snake',
    controls: 'Keyboard / Touch',
    accent: '#84cc16',
    setup: 'static',
  },
];
