/** @typedef {{ id: string, name: string, folder: string, entry: string, tagline: string, genre: string, controls: string, accent: string, image?: string, setup?: 'npm-build'|'vite-build'|'static', serveRoot?: string, packageDir?: string, playPath?: string, overrideEntry?: boolean }} GameDef */

/** @type {GameDef[]} */
module.exports = [
  {
    id: 'astray',
    name: 'Gravity Ball Escape',
    folder: 'Astray',
    entry: 'index.html',
    image: '/launcher/thumbs/astray.jpg',
    tagline: '3D maze. Find the exit before you lose your mind.',
    genre: 'Puzzle',
    controls: 'WASD / Arrows',
    accent: '#3dd6c3',
    setup: 'static',
  },
  {
    id: 'breaklock',
    name: 'BreakLock',
    folder: 'breaklock',
    serveRoot: 'breaklock/public',
    entry: 'index.html',
    image: '/launcher/thumbs/breaklock.jpg',
    playPath: '/breaklock/',
    tagline: 'Crack the pattern lock. Mastermind meets Android.',
    genre: 'Puzzle',
    controls: 'Touch / Mouse',
    accent: '#ff6b4a',
    setup: 'npm-build',
    packageDir: 'breaklock',
  },
  {
    id: 'hexgl',
    name: 'Hover Craft',
    folder: 'HexGL',
    entry: 'index.html',
    image: '/launcher/thumbs/hexgl.jpg',
    tagline: 'Futuristic WebGL racing at full throttle.',
    genre: 'Racing',
    controls: 'Arrows / WASD',
    accent: '#5b8cff',
    setup: 'static',
  },
  {
    id: 'hextris',
    name: 'Hextris',
    folder: 'hextris',
    entry: 'index.html',
    image: '/launcher/thumbs/hextris.jpg',
    tagline: 'Rotate the hex. Stack colors. Chase a high score.',
    genre: 'Arcade',
    controls: 'Left / Right',
    accent: '#c4f542',
    setup: 'static',
  },
  {
    id: 'mimstris',
    name: 'Mimstris',
    folder: 'mimstris',
    serveRoot: 'mimstris/dist',
    entry: 'index.html',
    image: '/launcher/thumbs/mimstris.jpg',
    tagline: 'Tetris-inspired puzzle chaos built with React.',
    genre: 'Puzzle',
    controls: 'WASD / Arrows / Enter',
    accent: '#ff4d8d',
    setup: 'vite-build',
    packageDir: 'mimstris',
  },
  {
    id: 'mk-js',
    name: 'Mortal Combat',
    folder: 'mk.js',
    serveRoot: 'mk.js/game',
    entry: 'index.html',
    image: '/launcher/thumbs/mk-js.jpg',
    tagline: 'Canvas fighter — local 2-player brawler.',
    genre: 'Fighting',
    controls: 'Keyboard (P1 & P2)',
    accent: '#e85d04',
    setup: 'static',
    overrideEntry: true,
  },
  {
    id: 'pacman-canvas',
    name: 'Pacman',
    folder: 'pacman-canvas',
    entry: 'index.htm',
    image: '/launcher/thumbs/pacman-canvas.jpg',
    tagline: 'Classic pac-dot chasing on HTML5 canvas.',
    genre: 'Arcade',
    controls: 'Arrows',
    accent: '#ffe566',
    setup: 'static',
  },
  {
    id: 'radius-raid',
    name: 'Radius Raid',
    folder: 'radius-raid-js13k',
    entry: 'index.html',
    image: '/launcher/thumbs/radius-raid.jpg',
    tagline: 'Bullet-hell survival from a js13k entry.',
    genre: 'Shooter',
    controls: 'Mouse / WASD',
    accent: '#7cf5ff',
    setup: 'static',
  },
  {
    id: 'tower-game',
    name: 'Tower Game',
    folder: 'tower_game',
    entry: 'index.html',
    image: '/launcher/thumbs/tower-game.jpg',
    tagline: 'Swing blocks. Stack a skyscraper. Don’t drop.',
    genre: 'Arcade',
    controls: 'Tap / Click',
    accent: '#f95240',
    setup: 'npm-build',
    packageDir: 'tower_game',
  },
  {
    id: 'typer',
    name: 'Typer',
    folder: 'typer',
    entry: 'typer.html',
    image: '/launcher/thumbs/typer.jpg',
    tagline: 'Type to shoot. Tower-defense typing frenzy.',
    genre: 'Typing',
    controls: 'Keyboard',
    accent: '#2ec4b6',
    setup: 'static',
  },
  {
    id: 'dino-adventure',
    name: 'Dino Adventure',
    folder: 'Dino Adventure',
    entry: 'previews.customer.envatousercontent.com/files/366391597/index.html',
    image: '/launcher/thumbs/dino-adventure.jpg',
    tagline: 'Little Dino Adventure (Construct 3)',
    genre: 'Adventure',
    controls: 'Touch / Keyboard',
    accent: '#5eead4',
    setup: 'static',
  },
];
